### ISSUE TITLE
Bug: Cannot access federated share folder

### ISSUE THREAD

**Issue by andreasfk** [nextcloud/vo_federation#26]
App Version: 0.1.3

When receiving a federated share, shared folders cannot be accessed.

There are two different behaviours for preexisting default folders (Templates, Media) and newly created folders.

Preexisting folders:
"This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client."
![grafik](https://user-images.githubusercontent.com/21079312/211824108-ca3029a4-8458-4939-af9b-68140229bc09.png)

Newly created folders:
"Page not found"
![grafik](https://user-images.githubusercontent.com/21079312/211824447-02d8727f-25cb-455d-bb0f-8e0905111404.png)

**Comment by andreasfk** [comment]
Bug still present in 0.1.4

**Comment by smesterheide** [comment]
Works locally in my dev environment and does not seem to be a big issue as folder shares are generally not much different than file shares. Possibly the root cause is the same as described here: https://github.com/nextcloud/vo_federation/issues/13#issuecomment-1384495836

**Comment by smesterheide** [comment]
The fix is applied on the test server.

It turns out the problem was twofold. a) Since the introduction of background jobs the server could not resolve its own URL. This was fixed by setting `overwrite.cli.url`. b) Longer URNs could not be stored on the remote instance due to DB column limitation. This was also fixed by a server update.

**Comment by andreasfk** [comment]
Issue is fixed.
