### ISSUE TITLE
Bug: Share not visible in files app

### ISSUE THREAD

**Issue by andreasfk** [nextcloud/vo_federation#29]
Sometimes (or even always) on the sharee's side, the share is visible in the share overview but not in the files overview.

**Comment by smesterheide** [comment]
I think this happens when the share is accepted but the WebDAV propfind call fails. As there was a problem with remote shares generally, I would ask to try again and monitor any problems. See also https://github.com/nextcloud/vo_federation/issues/26#issuecomment-1386617985

Furthermore I will provide better ways to debug the system as an end user/tester with the next release.

**Comment by andreasfk** [comment]
Fixed in currently installed version.
